# Auto-generated Splunk admin password. The plaintext lives only in Terraform
# state (encrypted at rest in the S3 backend) and Secrets Manager. The cloud-init
# script reads it from Secrets Manager and writes it into user-seed.conf.
resource "random_password" "admin" {
  length  = 32
  special = false # Splunk's user-seed parser doesn't love every special char; keep alphanumeric.
}

resource "aws_secretsmanager_secret" "admin" {
  name        = "${var.name_prefix}/splunk-admin-password"
  description = "Splunk admin password (auto-generated by Terraform)"
  tags        = var.tags
}

resource "aws_secretsmanager_secret_version" "admin" {
  secret_id     = aws_secretsmanager_secret.admin.id
  secret_string = random_password.admin.result
}
